# Generated by Django 5.0 on 2025-09-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
        ),
    ]
