# Generated by Django 5.0 on 2025-10-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_style_preference',
            field=models.CharField(blank=True, choices=[('', 'No preference'), ('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='', help_text='Preferred work environment for new roles', max_length=10),
        ),
    ]
